---
- name: Updated apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install nginx
  apt: name={{ item }} state=present
  become: true
  with_items:
    - nginx
    - supervisor


- name: start nginx
  become: true
  service:
    name: nginx
    state: started

- name: start supervisor
  become: true
  service:
    name: supervisor
    state: started